# Titel und Beschreibung Ihrer Seite
title: ZETA
description: Dokumentation für das ZETA-Projekt der gematik.
url: "https://gematik.github.io/zeta" # Wichtig: Passen Sie dies an, sobald die Seite live ist
baseurl: "/ZETA"

# Theme-Auswahl: Just the Docs
# Wir verwenden remote_theme, damit GitHub Pages das Theme automatisch bezieht.
remote_theme: just-the-docs/just-the-docs

# Logo im Header (optional, aber empfohlen)
logo: "/images/gematik-logo.svg"
favicon_ico: "/images/favicon.ico"

# Suchfunktion aktivieren
#search_enabled: true

# Navigation aktivieren
just_the_docs:
  collections:
    api:
      permalink: /:collection/:path/
      output: true
  aux_links:
    "API Dokumentation": /api/
    "API Version 1": /api/v1/

# Standardeinstellungen für alle Seiten und Posts (optional, aber nützlich)
defaults:
  - scope:
      path: "" # für alle Dateien im Repo
    values:
      toc: true # Inhaltsverzeichnis (rechts) standardmäßig aktivieren