# Titel und Beschreibung Ihrer Seite
title: ZETA
description: Dokumentation für das ZETA-Projekt der gematik.
#url: "https://gematik.github.io" # Wichtig: Passen Sie dies an, sobald die Seite live ist
#baseurl: "/ZETA"

# Theme-Auswahl: Just the Docs
# Wir verwenden remote_theme, damit GitHub Pages das Theme automatisch bezieht.
remote_theme: just-the-docs/just-the-docs

# URL-Konfiguration für GitHub Pages
# WICHTIG: url ist NUR die Domain, baseurl ist das Repository
url: "https://gematik.github.io"
baseurl: "/ZETA"

# Logo im Header
logo: "/images/gematik-logo.svg" # Pfad zu Ihrem Logo, ggf. anpassen
favicon_ico: "/images/favicon.ico" # Pfad zu Ihrem Favicon, ggf. anpassen

# Suchfunktion aktivieren (empfohlen)
search_enabled: true
