title: ZETA API Dokumentation
description: Offizielle API Dokumentation für das ZETA Projekt der gematik.

remote_theme: just-the-docs/just-the-docs

url: "https://gematik.github.io"
baseurl: "/ZETA"

plugins:
  - jekyll-redirect-from

# Defaults-Block
defaults:
  - scope:
      path: ""
      type: "v1"
    values:
      layout: "default"
      parent: "ZETA API Dokumentation"
